# Generated by Django 2.2 on 2019-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190416_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
