# Generated by Django 2.2 on 2019-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190418_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterprofile',
            old_name='title',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='masterprofile',
            old_name='photo',
            new_name='gallery',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='dob',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
