# Generated by Django 2.2 on 2019-04-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190423_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service', models.ManyToManyField(to='booking.MasterProfile')),
            ],
            options={
                'verbose_name': 'ServiceType',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
