# Generated by Django 2.2 on 2019-04-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_servicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='service',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='services',
            field=models.ManyToManyField(to='booking.ServiceType'),
        ),
    ]
