# Generated by Django 2.2 on 2019-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190426_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
