# Generated by Django 2.2 on 2019-04-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190426_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='master',
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.Schedule'),
        ),
    ]
