# Generated by Django 2.2 on 2019-05-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190426_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.ManyToManyField(related_name='book', to='booking.MasterProfile'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='booking.MasterProfile'),
        ),
    ]
