# Generated by Django 2.2 on 2019-05-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190504_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='master',
        ),
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='booking.MasterProfile'),
        ),
    ]
